*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 04.05.2012 at 14:54:45 by user 10106
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDBSTOP.                          " Global Data
  INCLUDE LZDBSUXX.                          " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDBSF00                                . " subprograms
  INCLUDE LZDBSI00                                . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDBSF...                          " Subprograms
* INCLUDE LZDBSO...                          " PBO-Modules
* INCLUDE LZDBSI...                          " PAI-Modules
