*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 04.05.2012 at 15:45:05 by user 10106
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDELLUSRTOP.                      " Global Data
  INCLUDE LZDELLUSRUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDELLUSRF00                            . " subprograms
  INCLUDE LZDELLUSRI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDELLUSRF...                      " Subprograms
* INCLUDE LZDELLUSRO...                      " PBO-Modules
* INCLUDE LZDELLUSRI...                      " PAI-Modules
